user_homepage:
    path:     /user/
    defaults: { _controller: UserBundle:User:index }

login:
    path: /login
    defaults: { _controller: 'UserBundle:Security:login' }
    methods:  [GET, POST]

logout:
    path: /logout
